// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectSupportSystem.Data;

namespace ProjectSupportSystem.Migrations
{
    [DbContext(typeof(ProjectSupportSystemContext))]
    partial class ProjectSupportSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectSupportSystem.Data.Category", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublicSupport")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ProjectSupportSystem.Data.SupPropSupElem", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SupportElementID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SupportPropertyID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("SupportElementID");

                    b.HasIndex("SupportPropertyID");

                    b.ToTable("SupPropSupElems");
                });

            modelBuilder.Entity("ProjectSupportSystem.Data.Support", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SupportPropertyID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("SupportPropertyID");

                    b.ToTable("Supports");
                });

            modelBuilder.Entity("ProjectSupportSystem.Data.SupportElement", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SupPropSupElemID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SupportElementAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SupportElementName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupportElementPercentage")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("SupportElements");
                });

            modelBuilder.Entity("ProjectSupportSystem.Data.SupportProperty", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationProcessAndCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Goal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SupPropSupElemID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SupportAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SupportDuration")
                        .HasColumnType("int");

                    b.Property<string>("SupportName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupportPercentage")
                        .HasColumnType("int");

                    b.Property<string>("WhoApply")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("SupportProperties");
                });

            modelBuilder.Entity("ProjectSupportSystem.Data.SupPropSupElem", b =>
                {
                    b.HasOne("ProjectSupportSystem.Data.SupportElement", "SupportElementOfSupPropSupElem")
                        .WithMany("SupPropElemsOfSupportElement")
                        .HasForeignKey("SupportElementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectSupportSystem.Data.SupportProperty", "SupportPropertyOfSupPropSupElem")
                        .WithMany("SupPropElemsOfSupportProperty")
                        .HasForeignKey("SupportPropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectSupportSystem.Data.Support", b =>
                {
                    b.HasOne("ProjectSupportSystem.Data.Category", "CategoryOfSupport")
                        .WithMany("Supports")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectSupportSystem.Data.SupportProperty", "SupportPropertyOfSupport")
                        .WithMany("Supports")
                        .HasForeignKey("SupportPropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
