// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectSupportSystem.Models;

namespace ProjectSupportSystem.Migrations
{
    [DbContext(typeof(ProjectSupportSystemContext))]
    partial class ProjectSupportSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectSupportSystem.Models.Support", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationProcessAndCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Goal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SupportAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SupportDuration")
                        .HasColumnType("int");

                    b.Property<string>("SupportName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupportPercentage")
                        .HasColumnType("int");

                    b.Property<int>("SupportSupElementID")
                        .HasColumnType("int");

                    b.Property<string>("SupportType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhoApply")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Supports");
                });

            modelBuilder.Entity("ProjectSupportSystem.Models.SupportElement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SupportElementAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SupportElementName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupportElementPercentage")
                        .HasColumnType("int");

                    b.Property<int>("SupportSupElementID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("SupportElements");
                });

            modelBuilder.Entity("ProjectSupportSystem.Models.SupportSupElement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupportElementID")
                        .HasColumnType("int");

                    b.Property<int>("SupportID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SupportElementID");

                    b.HasIndex("SupportID");

                    b.ToTable("SupportSupElements");
                });

            modelBuilder.Entity("ProjectSupportSystem.Models.SupportSupElement", b =>
                {
                    b.HasOne("ProjectSupportSystem.Models.SupportElement", "SupportElementOfSupportSupElement")
                        .WithMany("SupportsOfSupportSupElement")
                        .HasForeignKey("SupportElementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectSupportSystem.Models.Support", "SupportOfSupportSupElement")
                        .WithMany("SupportsOfSupportSupElement")
                        .HasForeignKey("SupportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
